//! `brokk` — the Brokkr command-line interface.
//!
//! Phase 1: `version`, stub `init`, and `run --command "..."` for the
//! end-to-end happy path.

use std::path::PathBuf;

use anyhow::{anyhow, Context, Result};
use brokkr_sdk::{run_command, BrokkrClient, TlsConfig};
use clap::{Parser, Subcommand};

/// Top-level CLI entrypoint.
#[derive(Debug, Parser)]
#[command(
    name = "brokk",
    version,
    about = "Brokkr — distributed build & compute grid",
    long_about = None,
    arg_required_else_help = true,
)]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Print the brokk version, target triple, and embedded git revision.
    Version,
    /// Initialize a Brokkr project in the current directory.
    Init {
        /// Overwrite existing config files.
        #[arg(long)]
        force: bool,
    },
    /// Run a shell command on the cluster.
    Run {
        /// Control plane endpoint (e.g. `http://127.0.0.1:7878`).
        #[arg(long, default_value = "http://127.0.0.1:7878")]
        control: String,

        /// Skip the action cache lookup and force re-execution.
        #[arg(long)]
        no_cache: bool,

        /// CA certificate for verifying the control plane server certificate.
        #[arg(long)]
        tls_ca: Option<String>,

        /// Client certificate for mTLS authentication (requires --tls-client-key).
        #[arg(long, requires = "tls_client_key")]
        tls_client_cert: Option<String>,

        /// Client private key for mTLS authentication (requires --tls-client-cert).
        #[arg(long, requires = "tls_client_cert")]
        tls_client_key: Option<String>,

        /// JWT bearer token sent in `authorization: Bearer <token>` on
        /// every outbound RPC. Required when the control plane has
        /// `--auth-jwt-*` enabled (ADR 0011, issue #139). Mutually
        /// exclusive with `--bearer-token-file`.
        #[arg(long, conflicts_with = "bearer_token_file")]
        bearer_token: Option<String>,

        /// Path to a file containing the JWT bearer token. Preferred
        /// for tokens read from disk so they don't appear in `ps` or
        /// `/proc/<pid>/cmdline`. Mutually exclusive with
        /// `--bearer-token`. The file should contain the raw token
        /// bytes; trailing whitespace is trimmed.
        #[arg(long, conflicts_with = "bearer_token")]
        bearer_token_file: Option<PathBuf>,

        /// The command to run, including arguments. Pass via repeated
        /// positional args: `brokk run -- echo hello world`.
        #[arg(trailing_var_arg = true, required = true)]
        argv: Vec<String>,
    },
}

fn main() -> Result<()> {
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let cli = Cli::parse();
    match cli.command {
        Command::Version => print_version(),
        Command::Init { force } => init_project(force),
        Command::Run {
            control,
            no_cache,
            tls_ca,
            tls_client_cert,
            tls_client_key,
            bearer_token,
            bearer_token_file,
            argv,
        } => run_subcmd(RunOptions {
            control,
            no_cache,
            tls: TlsOptions {
                ca: tls_ca,
                client_cert: tls_client_cert,
                client_key: tls_client_key,
            },
            bearer: BearerOptions {
                token: bearer_token,
                token_file: bearer_token_file,
            },
            argv,
        }),
    }
}

fn print_version() -> Result<()> {
    println!(
        "brokk {} ({})\nrustc: {}\ntarget: {}",
        env!("CARGO_PKG_VERSION"),
        option_env!("BROKKR_GIT_SHA").unwrap_or("unknown"),
        env!("BROKKR_RUSTC_VERSION"),
        env!("BROKKR_TARGET_TRIPLE"),
    );
    Ok(())
}

const BROKK_TOML_CONTENT: &str = r#"# Brokkr workspace configuration.
# Generated by `brokk init`. Edit to taste.

[workspace]
# Default control plane endpoint.
control_endpoint = "http://127.0.0.1:7878"

# Worker lease TTL in seconds.
lease_ttl_secs = 60
"#;

const BROKKIGNORE_CONTENT: &str = r#"# brokkr local state
.brokkr/

# Build artifacts
**/target/

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db
"#;

const WORKFLOW_YAML: &str = r#"name: brokkr

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
      - run: cargo test --workspace
"#;

/// Write a scaffolding file to `path`, failing if it already exists
/// unless `force` is true.
fn scaffold_file(path: &std::path::Path, content: &str, force: bool) -> Result<()> {
    if path.exists() && !force {
        return Err(anyhow!(
            "{} already exists; pass --force to overwrite",
            path.display()
        ));
    }
    std::fs::write(path, content).with_context(|| format!("writing {}", path.display()))?;
    println!("  created {}", path.display());
    Ok(())
}

/// Scaffold brokk configuration files in the current directory.
pub fn init_project(force: bool) -> Result<()> {
    let cwd = std::env::current_dir().context("getting current directory")?;
    println!("brokk init: scaffolding in {}", cwd.display());

    scaffold_file(&cwd.join("brokk.toml"), BROKK_TOML_CONTENT, force)?;
    scaffold_file(&cwd.join(".brokkrignore"), BROKKIGNORE_CONTENT, force)?;

    let workflow_dir = cwd.join(".github").join("workflows");
    std::fs::create_dir_all(&workflow_dir)
        .with_context(|| format!("creating {}", workflow_dir.display()))?;
    scaffold_file(&workflow_dir.join("brokkr.yml"), WORKFLOW_YAML, force)?;

    println!("brokk init: done");
    Ok(())
}

/// TLS-related CLI options for `brokk run`. Bundled to keep the
/// `run_subcmd` signature below clippy's `too_many_arguments` threshold.
#[derive(Debug, Default)]
struct TlsOptions {
    ca: Option<String>,
    client_cert: Option<String>,
    client_key: Option<String>,
}

/// Bearer-token CLI options for `brokk run`. Mutually exclusive at the
/// clap layer (`conflicts_with`); we materialise one of three states
/// (`Token`, `TokenFile`, `None`) into the resolved token in
/// `run_subcmd`.
#[derive(Debug, Default)]
struct BearerOptions {
    token: Option<String>,
    token_file: Option<PathBuf>,
}

/// Everything `run_subcmd` needs from the CLI layer. Bundled for the
/// same reason as [`TlsOptions`] and [`BearerOptions`].
struct RunOptions {
    control: String,
    no_cache: bool,
    tls: TlsOptions,
    bearer: BearerOptions,
    argv: Vec<String>,
}

fn run_subcmd(opts: RunOptions) -> Result<()> {
    if opts.argv.is_empty() {
        return Err(anyhow!("`brokk run` requires a command"));
    }

    // Runtime validation: partial mTLS identity is an error.
    let has_cert = opts.tls.client_cert.is_some();
    let has_key = opts.tls.client_key.is_some();
    if has_cert != has_key {
        anyhow::bail!("both --tls-client-cert and --tls-client-key must be provided together");
    }
    if (has_cert || has_key) && opts.tls.ca.is_none() {
        anyhow::bail!("--tls-client-cert and --tls-client-key require --tls-ca to be provided");
    }

    // Resolve bearer token: `--bearer-token` wins if both are somehow set,
    // but `conflicts_with` on the clap args should already prevent that.
    let bearer = match (opts.bearer.token, opts.bearer.token_file) {
        (Some(t), _) => Some(t),
        (None, Some(path)) => Some(
            std::fs::read_to_string(&path)
                .with_context(|| format!("reading bearer token from {}", path.display()))?
                .trim()
                .to_string(),
        ),
        (None, None) => None,
    };

    let tls = opts.tls.ca.map(|ca| TlsConfig {
        ca_cert: std::path::PathBuf::from(ca),
        client_cert: opts.tls.client_cert.map(std::path::PathBuf::from),
        client_key: opts.tls.client_key.map(std::path::PathBuf::from),
    });

    let control = opts.control;
    let argv = opts.argv;
    let no_cache = opts.no_cache;

    let rt = tokio::runtime::Runtime::new().context("starting tokio runtime")?;
    rt.block_on(async move {
        // Connect with the right combination: TLS, bearer, or both.
        // The `(tls, bearer)` matrix is exhaustive: 0..=1 of each may be
        // set; we materialise it into four branches to keep the call
        // sites readable. The control plane refuses to start in any
        // combination that would silently mis-configure auth (issue
        // #139), so a wrong client-side combo just surfaces as a
        // runtime `UNAUTHENTICATED` here.
        let mut client = match (tls, bearer) {
            (Some(tls_cfg), Some(token)) => {
                BrokkrClient::connect_with_tls_and_bearer(control, tls_cfg, token).await?
            }
            (Some(tls_cfg), None) => BrokkrClient::connect_with_tls(control, tls_cfg).await?,
            (None, Some(token)) => BrokkrClient::connect_with_bearer(control, token).await?,
            (None, None) => BrokkrClient::connect(control).await?,
        };
        let outcome = run_command(&mut client, &argv, no_cache).await?;
        // Forward stdout/stderr verbatim to the user's terminal.
        use std::io::Write as _;
        std::io::stdout().write_all(&outcome.stdout)?;
        std::io::stderr().write_all(&outcome.stderr)?;
        eprintln!(
            "[brokk] exit={} cache_hit={}",
            outcome.exit_code, outcome.cache_hit
        );
        std::process::exit(outcome.exit_code);
    })
}
